[project]
name = "sbtc-payment-processor"
authors = []
description = "Decentralized sBTC and STX payment gateway for merchants."
telemetry = false
requirements = []

[contracts.payment]
path = "contracts/payment.clar"
clarity_version = 

[contracts.sbtc-token
path = "contracts/test-utils/sbtc-token.clar
clarity_version = 
[networks.m
rpc_bind = "https://a
stacked_node_rpc_bind = "https://api.hiro

[repl.analysi
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
